### PR TITLE
Added dom-repeat support

### PR DESCRIPTION
**Pull request by JaySunSyn**
Utilizing items property of iron-selector.
Added also a demo and adjusted tests.

### CODE REVIEW

**Comment by JaySunSyn** [comment]
Not sure whats the problem with travis

**Comment by ernysans** [comment]
@stivaliserna Please review this.

**Comment by stivaliserna** [comment]
> Not sure whats the problem with travis

Hi, @JaySunSyn 

Please, fix linting errors first and you can run locally `npm run lint` and `npm run test`.

**Comment by stivaliserna** [comment]
> Please, fix linting errors first and you can run locally npm run lint and npm run test.

Nvm, I didn't see you already fix them.

**Comment by stivaliserna** [comment]
@JaySunSyn Some images are not loading running the demo locally, can you double check?

image

**Comment by ernysans** [comment]
@stivaliserna Please check out this again.

**Comment by ernysans** [comment]
@JaySunSyn Your code had some problems and this wasn't the best solution for the problem.
Thans for the PR but I was able to get a better solution on PR #55

**Pull request closed without merging**
